Main page
whattablackhole/rslang pull request #1
Opened 2022-08-28 08:31 UTC by nvfnvm

1. вёрстка, дизайн, UI главной страницы приложения
2. главная страница приложения содержит:
3. меню с навигацией по учебнику, ссылками на мини-игры и статистику. Меню или иконка меню отображается на всех страницах приложения
4. описание возможностей и преимуществ приложения
5. раздел "О команде" с фото или аватарками и ссылками на гитхабы всех участников команды, описанием вклада в разработку приложения каждого из них. При желании данный раздел можно вынести в отдельную страницу
footer со ссылками на гитхабы авторов приложения, год создания приложения, [логотип курса](https://rs.school/images/rs_school_js.svg) со [ссылкой на курс](https://rs.school/js/). footer отображается на всех страницах приложения за исключением мини-игр

2022-08-28 17:01 UTC, Konstantsin-Shumak requested changes

2022-08-28 17:01 UTC, Konstantsin-Shumak commented on rslang/src/App.ts
> +import { TestComponents } from "./components/TestComponents/TestComponents";
Rename component by logical

2022-08-28 17:01 UTC, Konstantsin-Shumak commented on rslang/src/components/TestComponents/TestComponents.ts
> +    </div>`
Lots of duplicate code

2022-08-28 17:01 UTC, Konstantsin-Shumak commented on rslang/src/components/TestComponents/TestComponents.ts
> +    //Main
Split your page by components.

Example: header, main, footer etc

2022-08-29 13:49 UTC, whattablackhole approved these changes

2022-08-29 13:49 UTC, whattablackhole commented on rslang/src/App.ts
> +  testComponents = new TestComponents();
why it has name 'Test'?

2022-08-29 13:49 UTC, whattablackhole commented on rslang/src/components/TestComponents/TestComponents.ts
> +/* eslint-disable no-mixed-spaces-and-tabs */
do you want to ignore this rule only for this particular file?
If not, add this rule to eslintrc

2022-08-29 13:49 UTC, whattablackhole commented on rslang/src/components/TestComponents/TestComponents.ts
> +/* eslint-disable no-mixed-spaces-and-tabs */
Seems that all you have to do to avoid this error is to download the eslint extension and use auto corrections for spaces and tabs
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

2022-08-29 13:49 UTC, whattablackhole commented on rslang/src/components/TestComponents/TestComponents.ts
> +    const headerMenu = document.querySelector('.header_menu') as HTMLElement;
It's bad practice, as you can create element and keep it reference to avoid additional query for it.
Let's create seperate file e.g HeaderMenu.js and export function which returns element or directly element.

2022-08-29 13:49 UTC, whattablackhole commented on rslang/src/components/TestComponents/TestComponents.ts
> +    const headerMenu = document.querySelector('.header_menu') as HTMLElement;
As you have limited time, you can keep it in mind and refactor later

2022-08-29 18:10 UTC, zzzhuchok approved these changes

2022-08-29 18:10 UTC, zzzhuchok commented on rslang/src/components/TestComponents/main.css
> +body > footer > .footer_wrapper > div.devs_git > span > a {
why is there such a chain of selectors?

2022-08-30 10:59 UTC, Konstantsin-Shumak approved these changes

2022-08-30 11:08 UTC, merged